import type { EquipmentSlot } from "../types/study";

export type HeroSiegeItemCategory = {
  id: string;
  label: string;
  names: readonly string[];
  slot: EquipmentSlot;
  sourceSection: string;
};

export const HERO_SIEGE_ITEM_CATEGORIES = [
  {
    "id": "normal-axes",
    "sourceSection": "Normal Axes",
    "slot": "mainHand",
    "label": "Normal Axes",
    "names": [
      "Hand Axe",
      "Hatchet",
      "Naga",
      "Broad Axe",
      "War Axe",
      "Giant Axe"
    ]
  },
  {
    "id": "normal-maces",
    "sourceSection": "Normal Maces",
    "slot": "mainHand",
    "label": "Normal Maces",
    "names": [
      "Cudgel",
      "Mace",
      "Morning Star",
      "Spiked Club",
      "War Hammer",
      "Maul",
      "Ogre Maul",
      "Martel De Fer",
      "Flail",
      "Devil Star"
    ]
  },
  {
    "id": "normal-daggers",
    "sourceSection": "Normal Daggers",
    "slot": "mainHand",
    "label": "Normal Daggers",
    "names": [
      "Dagger",
      "Dirge",
      "Kris"
    ]
  },
  {
    "id": "normal-swords",
    "sourceSection": "Normal Swords",
    "slot": "mainHand",
    "label": "Normal Swords",
    "names": [
      "Short Sword",
      "Sabre",
      "Claymore",
      "Broad Sword",
      "Scimitar",
      "Giant Sword",
      "Katana",
      "War Sword",
      "Falchion",
      "Flamberge",
      "Zangetsu"
    ]
  },
  {
    "id": "weapon-melee-unique",
    "sourceSection": "weapon_melee_unique",
    "slot": "mainHand",
    "label": "Unique Melee Weapons",
    "names": [
      "Godfather",
      "Jade Warrior's Gladius",
      "Storm Katana",
      "Molten Sword",
      "Inferno Slayer",
      "Dragon Knight's Flail",
      "Rift Commander's Axe",
      "The Undying",
      "Shattered Dimensions",
      "Ashbringer",
      "Death's Mirror",
      "Odin's Battle Axe",
      "Gurag's Stone Crusher",
      "Death's Scythe",
      "Hiyoki's Vorpal Katana",
      "Hanzo's Flaming Katana",
      "Genji's Sword of Fate",
      "Wind Guardian's Gladius",
      "Sand Crusader's Scimitar",
      "Azure's Wrath",
      "Holy Warrior's Phase Blade",
      "Steve's Mighty Sword",
      "St. Gabriel's Retribution",
      "Thor's Battle Sword",
      "Viking's Sacred Axe",
      "Nomad's Sandslicer",
      "Nobunaga's Battle Slicer",
      "Molten Dagger",
      "Icy Shank",
      "Darkness",
      "Gladiator's Wrecking Ball",
      "Dante's Demon Blade",
      "Shadow Carver",
      "Sacred Whip",
      "Nightmare Slasher",
      "Frozen Carver",
      "Unholy God's Flail",
      "Molten Hammer",
      "Icy Crusher",
      "The Light of Dawn",
      "Gladiator's Skullcrusher",
      "Masamune",
      "Muramasa",
      "Crystal Infused Axe",
      "Crystal Infused Sword",
      "Sung Lee's Destroyer Flail",
      "Revenant's Lasher",
      "Bonetti's Rapier",
      "Eternal Glaive",
      "Gut's BFS",
      "St. Rexis Sundering Axe",
      "Sand Dagger",
      "Thunder Dagger",
      "Riftmaster's Dirge",
      "St. Mika's Zweihänder",
      "Sanguine Blade",
      "Pillar of Niflheim",
      "Grimbone's Scythe",
      "Ceremonial Dagger",
      "Spiritus",
      "Gut's HFS",
      "Sähköpuimuri",
      "Arch Angel's Phase Blade",
      "Gem King's Cleaver",
      "Winter's Bite",
      "Wraith Forged Cleaver",
      "Aurelion Fury",
      "Abomination's Gut Ripper",
      "Rakhul's Legion Crusher",
      "Daisy",
      "The Dawn Bringer",
      "Gabriel's Broken Resolve",
      "The Hope Ender",
      "Luci's Day",
      "Glowstick Estoc",
      "Headsman´s Bloodthirster",
      "Shishkebab",
      "Stormslayer",
      "Blood Moon Crescent",
      "Stofflix Cooking Cleaver",
      "Doom Cutter",
      "Pit Fighter´s Skullcracker",
      "Pit Fighter´s Brutalizer",
      "Metal Vocalist´s Warlock",
      "Fenrir´s Bloodfang"
    ]
  },
  {
    "id": "weapon-throwing",
    "sourceSection": "weapon_throwing",
    "slot": "mainHand",
    "label": "Throwing Weapons",
    "names": [
      "Throwing Axe",
      "Battle Darts",
      "Throwing Disc",
      "Harpoon",
      "Javelin",
      "Pilum",
      "Simbilan",
      "Short Spear",
      "Throwing Spear"
    ]
  },
  {
    "id": "weapon-throwing-unique",
    "sourceSection": "weapon_throwing_unique",
    "slot": "mainHand",
    "label": "Unique Throwing Weapons",
    "names": [
      "Mimir's Corrupted Axe",
      "Scarred Battle Darts",
      "Wakayka's Tomahawk",
      "Imperial Glaive",
      "Ukko's Revenge",
      "Wargod's Wrath",
      "St. Neri's Rainbow Lance",
      "Serpent's Tooth",
      "Crystal Infused Javelin",
      "Valkyrie's Thunder Javelin",
      "Deep Sea Glaive",
      "Sowyer's Javelin of Devastation",
      "Sidewinder"
    ]
  },
  {
    "id": "weapon-spell",
    "sourceSection": "weapon_spell",
    "slot": "mainHand",
    "label": "Spell Weapons",
    "names": [
      "Gnarled Staff",
      "Cane",
      "Arcane Fork",
      "Spellblade",
      "Wand",
      "Magic Tome",
      "Yew Wand"
    ]
  },
  {
    "id": "weapon-spell-unique",
    "sourceSection": "weapon_spell_unique",
    "slot": "mainHand",
    "label": "Unique Spell Weapons",
    "names": [
      "Spellshard",
      "The Iris",
      "Staff of Nether Flame",
      "Archangel Staff",
      "Oculus of Ages",
      "God's Benevolence",
      "Satan's Unholy Bible",
      "Book of Revelations",
      "Damien's Head",
      "Clafaxier",
      "Raise of the Dead",
      "Dragon's Breath",
      "Apocalypto",
      "Steve's Wand of Fortune",
      "St. HouDeanii's Tiny Fire Rod",
      "Wormclaw",
      "Beacon of Shadows",
      "Crystal Infused Wand",
      "Zealot's Book of Prophecy",
      "Uabel's Wand",
      "Battle Mage's Wand",
      "Spell Eater",
      "Blood of Abaddon",
      "Ancient Sun Beacon",
      "The Eye of Tarethiel",
      "Sands of Time",
      "Crystal Cane of Ice",
      "Cane of the Tundra",
      "Book of Cold Death",
      "Thorn of Helheim",
      "Flame of the Phoenix",
      "Hypothermia",
      "St. Nimo's Lightbringer",
      "Solar Prophet's Tablet",
      "Pagan God's Blasphemy",
      "Voodoo Magician's Skull",
      "Wraithbone",
      "Clafaxier's Legacy",
      "Manafunneler´s Conjurer",
      "Crackling Thunder",
      "Necrobutcher´s Curse",
      "Crow´s Whisper",
      "Damien´s Corrupted Head",
      "Witch´s Wand"
    ]
  },
  {
    "id": "weapon-bow",
    "sourceSection": "weapon_bow",
    "slot": "mainHand",
    "label": "Bows",
    "names": [
      "Crossbow",
      "Short War Bow",
      "Long Bow",
      "Gothic Bow"
    ]
  },
  {
    "id": "weapon-bow-unique",
    "sourceSection": "weapon_bow_unique",
    "slot": "mainHand",
    "label": "Unique Bows",
    "names": [
      "Buriza-ko-nu",
      "Wind's Force",
      "Poison Ivy",
      "Glimmerfury",
      "Flamebringer",
      "Steve's Punchbow",
      "St. Soloyolo's Holy Bow",
      "Marksman's Hunting Bow",
      "Shadowfury",
      "Electro",
      "Hellspawn Eradicator",
      "Deathquill",
      "Recurving Corrosion",
      "St. Amitiel's Truth",
      "Astral Projector",
      "Arachno Phobia",
      "Monsoon",
      "Arrow of Niflheim",
      "Eternity",
      "Arrow of Zamjo"
    ]
  },
  {
    "id": "weapon-claw",
    "sourceSection": "weapon_claw",
    "slot": "mainHand",
    "label": "Claws",
    "names": [
      "Wrist Blades",
      "Blade Talons",
      "Feral Claws"
    ]
  },
  {
    "id": "weapon-claw-unique",
    "sourceSection": "weapon_claw_unique",
    "slot": "mainHand",
    "label": "Unique Claws",
    "names": [
      "Storm Fury",
      "Molten Paw",
      "Hemorrhage",
      "Yoshi's Throat-Cutters",
      "Elemental Claws",
      "Talons of Wisdom",
      "Earth Shaper's Talons",
      "Spirit Walker's Guide",
      "Glacier Talons"
    ]
  },
  {
    "id": "weapon-polearm",
    "sourceSection": "weapon_polearm",
    "slot": "mainHand",
    "label": "Polearms",
    "names": [
      "Spear",
      "Tribal Spear",
      "Royal Lance",
      "War Trident",
      "Battle Lance",
      "Hyperion Spear",
      "Yari",
      "Fuscina",
      "War Spear"
    ]
  },
  {
    "id": "weapon-spear-unique",
    "sourceSection": "weapon_spear_unique",
    "slot": "mainHand",
    "label": "Unique Spears",
    "names": [
      "Crusader Halberd",
      "Poseidon's Might",
      "Odin's Battle Spear",
      "Vanguard's Lance",
      "War God's Lance",
      "Jousting Lance",
      "Golden God's Gladius",
      "St. Draxis' Pigstick",
      "Lancer's Glory",
      "Champion's Flag Lance",
      "Dark Knight's Lance",
      "Brimskull Trident",
      "Thorn of Noxus"
    ]
  },
  {
    "id": "weapon-gun",
    "sourceSection": "weapon_gun",
    "slot": "mainHand",
    "label": "Guns",
    "names": [
      "Hand Cannon",
      "Hunting Rifle",
      "Gatling Gun",
      "Battle Blaster"
    ]
  },
  {
    "id": "weapon-gun-unique",
    "sourceSection": "weapon_gun_unique",
    "slot": "mainHand",
    "label": "Unique Guns",
    "names": [
      "RT XQC-4910",
      "Vampire Hunter",
      "Flamecannon",
      "Warbringer",
      "Jack",
      "Fred",
      "Steve's Bang",
      "Chills of War",
      "Commander´s Sentry Blaster",
      "Marine's Buddy",
      "Demon",
      "Angel",
      "Crystal Infused Pistol",
      "F4-Tactical Rifle",
      "Dreadnought",
      "AK-47",
      "Glock 22",
      "Dracula´s Demise"
    ]
  },
  {
    "id": "weapon-chainsaw",
    "sourceSection": "weapon_chainsaw",
    "slot": "mainHand",
    "label": "Chainsaws",
    "names": [
      "Battle Slicer",
      "War Saw",
      "Trunk Cutter",
      "Hand Saw"
    ]
  },
  {
    "id": "weapon-chainsaw-unique",
    "sourceSection": "weapon_chainsaw_unique",
    "slot": "mainHand",
    "label": "Unique Chainsaws",
    "names": [
      "Sawgun",
      "Doublesaw 4000",
      "Doomsaw",
      "Vorpal Sharktooth",
      "The Annihilator",
      "St. Draxis Longsaw",
      "Lumberjack's Chainsaw",
      "Candy Shredder",
      "Royal Decapitator",
      "Diablo",
      "Eden´s Harvester"
    ]
  },
  {
    "id": "weapon-flask",
    "sourceSection": "weapon_flask",
    "slot": "mainHand",
    "label": "Weapon Flasks",
    "names": [
      "Poison Flask",
      "Caustic Vial",
      "Acid Flask",
      "Alchemist's Flask"
    ]
  },
  {
    "id": "weapon-flask-unique",
    "sourceSection": "weapon_flask_unique",
    "slot": "mainHand",
    "label": "Unique Weapon Flasks",
    "names": [
      "Cobra Blood Vial",
      "Ancient Mucus",
      "Demon Blood Flask",
      "Spirit Urn",
      "Doctor's Potion",
      "Doomweed Vial"
    ]
  },
  {
    "id": "weapon-universal",
    "sourceSection": "weapon_universal",
    "slot": "mainHand",
    "label": "Universal Weapons",
    "names": [
      "Lemon",
      "Fishing Rod",
      "Voided Item"
    ]
  },
  {
    "id": "armors",
    "sourceSection": "armors",
    "slot": "armor",
    "label": "Armor",
    "names": [
      "Steel Armor",
      "Leather Coat",
      "Studded Leather",
      "Trellised Armor",
      "Breast Plate",
      "Cuirass",
      "Templar Coat",
      "Wire Fleece",
      "Boneweave",
      "Chaos Armor",
      "Dusk Shroud",
      "Great Hauberk"
    ]
  },
  {
    "id": "armors-unique",
    "sourceSection": "armors_unique",
    "slot": "armor",
    "label": "Unique Armor",
    "names": [
      "Heaven's Might",
      "Leviathan's Carcass",
      "Tayrel's Chestplate",
      "Uabel's Chest",
      "Marsh Shroud",
      "Gladiator's Demise",
      "Hellfire Cuirass",
      "Devil's Cocoon",
      "Mevius' Mighty Plate",
      "Anubis Torso",
      "Genji's Battle Armor",
      "Satan's Cuirass",
      "Sand King's Scarab",
      "Ice Howl's Cuirass",
      "Grandwizard's Robe",
      "Zeus' Body Armor",
      "Redneck's Shirt",
      "Pirate Captain's Shirt",
      "Death Lord's Bone Armor",
      "Thor's Chest Armor",
      "Cuirass of Blood",
      "Magister's Robe",
      "Nomad's Battlerobe",
      "Marksman's Hunting Shroud",
      "Upi's Sweetshirt",
      "Thunder Gladiator's Armor",
      "Nobunaga's Battle Cuirass",
      "Dante's Jacket",
      "Lancer's Chestplate",
      "Demon's Ribcage",
      "Sacred Robe",
      "Chestplate of Fire",
      "Lichbane",
      "St. Jupe's Plate of Command",
      "Traveler's Leather Jacket",
      "Gem King's Garb",
      "Engineer's Plated Vest",
      "Vagabond's Wraps",
      "Flame Diviner's Sanctum",
      "Blood-letter's Plate Body",
      "Venom's Ribcage",
      "Shield Bearer's Plated Armor",
      "Juggernaut's Glorious Plate",
      "Justiciar's Thunder Armor",
      "Lost Master's Platemail",
      "Earth Shaper's body",
      "Plunderer's Jacket",
      "Valkyrie's Battle Raiment",
      "Hazmat Suit",
      "Molten Steel Cataphract",
      "Tropical Storm",
      "Magic-Imbued Frozen Plate",
      "Zephy's Gown",
      "Mystique Allure",
      "Cocoon of the Berserker",
      "Giant Thorned Lizard Skin",
      "Noxious Hunter's Reward",
      "Empire's Military Plate",
      "Leather Muscle Breastplate",
      "Tundra Hunter's Long Coat",
      "Arcane Robes of Authority",
      "Thunder Guardian's Plate",
      "Tactical Flak Jacket",
      "Unearthed Esoteric Panoply",
      "Sheep King's Hide",
      "Clan Leader's Pride",
      "Elementalist's Silk Shroud",
      "Bandit Lord's Shroud",
      "Black Knight's Carapace",
      "Behemoth's Damascus Body",
      "Sand Manipulator's Kalasiris",
      "Ymir's Frozen Vestment",
      "Einar's Plated Armor",
      "Gabriel's Leather Trench Coat",
      "Grimbone's Ribcage",
      "Odin's Battlearmor",
      "Ironclad Protector",
      "Magiward Battlegear",
      "Wardbreaker Armor",
      "Aegisweave Robes",
      "Solar Prophet's Robes",
      "Stoneplate of Corruption",
      "Butcher's Apron",
      "Gabriel's Broken Wings",
      "Thunder Caller's Robe",
      "Muspelheim Guardian's Scorched Plate",
      "Venomsteel Carapace",
      "Isarius Ironthorn Breastplate",
      "Executioner's Cocoon",
      "Exiled Pagan´s Mantle",
      "Runemaster´s Mantle",
      "Glacial Gladiator´s Armor",
      "Magma Gladiator´s Armor",
      "Scourge Gladiator´s Armor",
      "Arcane Gladiator´s Armor",
      "Grand Arch Wizard´s Mantle",
      "Pit Fighter´s Band Shirt",
      "Dragon Knight´s Vanguard",
      "Wraith´s Cloak",
      "Arcanist´s Wrath",
      "Sharpshooter´s Cloak"
    ]
  },
  {
    "id": "helms",
    "sourceSection": "helms",
    "slot": "headgear",
    "label": "Helms",
    "names": [
      "Cap",
      "Casque",
      "Basinet",
      "War Hat",
      "Great Helm",
      "War Visage",
      "Shako",
      "Horned Helm",
      "Basilisk Skull"
    ]
  },
  {
    "id": "helms-unique",
    "sourceSection": "helms_unique",
    "slot": "headgear",
    "label": "Unique Helms",
    "names": [
      "Harlequinn's Crest",
      "Harlequinn's Veil",
      "The Colossal Avenger",
      "Demon Warlord's Helm",
      "The Bucket",
      "Sky Crusader Helm",
      "Helm of Dominator",
      "The Faceless Priest",
      "Uabel's Helmet",
      "Reaper's Hood",
      "Genji's Battle Helmet",
      "Mevius' Mighty Helmet",
      "Flame God's Helmet",
      "Ice King's Crown",
      "Zeus' Circlet",
      "Redneck's Cap",
      "Pirate Captain's Hat",
      "Death Lord's Crown",
      "Thor's Battle Cap",
      "Viking's Sacred Helmet",
      "Nomad's Sand Bandana",
      "Nobunaga's Battle Helmet",
      "Gladiator's Skullet",
      "Doctor's Visage",
      "Aztec Crown",
      "Wendigo Skull",
      "Judge, Jury & Executioner",
      "Death Knight's Visage",
      "Ancient Avenger",
      "Burning Gaze",
      "Sight Of The Gods",
      "Zealot's Guise of Doom",
      "Flame Diviner's Refuge",
      "Lumberjack's Safety Helm",
      "Blood-letter's Crown",
      "Venom's Skull",
      "Shield Bearer's Crown",
      "Juggernaut's Siege Helm",
      "Lost Master's Vision",
      "Valkyrie's Winged Helm",
      "Surgical Mask",
      "Battle Worn Visor",
      "Underworld's Skullbreaker",
      "Sand Traveler's Guise",
      "Crown of the Holy One",
      "Guise of the Dead",
      "Veil of Mystery",
      "Crown of the North",
      "Tenebris' Grievance",
      "Mask of the Beyond",
      "Pit Lord's Vanquisher",
      "Lava King's Lost Mask",
      "The Grand Champion",
      "Crown of Midnight",
      "Nikita's KJ-33 Helmet",
      "The Curator of Secrets",
      "Sheep King's Crown",
      "Warlord's Fury",
      "Witches Brimmed Hat",
      "Assassin's Hood",
      "Knight Captain's Helmet",
      "Chronomancer's Observance",
      "Sand Manipulator's Mask",
      "Ymir's Frozen Shroud",
      "Einar's Horned Helmet",
      "Gabriel's Brimmed Fedora",
      "Grimbone's Visage",
      "Odin's Eternal Visage",
      "Aetherweaver's Veil",
      "Sentinel's Headguard",
      "Executioner's Headplate",
      "Bloodthirster's Warhelm",
      "Mage's Starshroud",
      "Reaver's Headplate",
      "Juda's Broken Halo",
      "Solar Prophet's Crown",
      "Lunar Prophet's Tiara",
      "Butcher's Hood",
      "Gabriel's Dauntless Vision",
      "Thunder Caller's Veil",
      "High Roller´s Deathcrown",
      "Gaze of the Oblivion",
      "Eternal Death",
      "Metal Vocalist´s Leather Mask",
      "Dragon Knight´s Helmet",
      "Crown of Doom",
      "Lucifer´s Crown",
      "Mask of the Celestial",
      "Veil of Consecration"
    ]
  },
  {
    "id": "gloves",
    "sourceSection": "gloves",
    "slot": "bodyAccessory",
    "label": "Gloves",
    "names": [
      "Heavy Gloves",
      "Chain Gloves",
      "Gauntlets",
      "Leather Gloves",
      "Snakeskin Gloves",
      "Heavy Bracers",
      "War Gauntlets",
      "Devilhide Gloves",
      "Vampirebone Gloves",
      "Demonbraces",
      "Ogre Gauntlets",
      "Archmage Wraps"
    ]
  },
  {
    "id": "gloves-unique",
    "sourceSection": "gloves_unique",
    "slot": "bodyAccessory",
    "label": "Unique Gloves",
    "names": [
      "Shadow's Grasp",
      "Midas' Hands",
      "Scuttle Crab Gauntlets",
      "Warmaster's Tribal Paws",
      "Death's Grasp",
      "Anubis' Mighty Hands",
      "Mevius' Mighty Gauntlets",
      "Throat Cutters",
      "Thor's Battle Gloves",
      "Nomad's Sand Mitts",
      "Marksman's Hunting Gloves",
      "Doctor's Grasp",
      "Dante's Mitts",
      "Lancers Gauntlets",
      "Devil's Grasp",
      "Gloves of Wilderness",
      "Hands of Flame",
      "Conjurer Mitts",
      "Zealot's Deathbringers",
      "Bone Conjurer's Grips",
      "Lumberjack's Safety Gloves",
      "Blood-letter's Plated Gauntlet",
      "Venom's Talons",
      "Champion's Fighting Gloves",
      "Lost Master's Gauntlets",
      "Brawler's Fighting Mitts",
      "Shadow Occultist's Wraps",
      "Razor Knuckles",
      "Siege Breakers",
      "Spellweavers",
      "St. Ahto's Diamond Hands",
      "Uabel's Gloves",
      "Battle Worn Gauntlets",
      "Wisdom's Hold",
      "Imbued Mage Gloves",
      "Battle Caster's Gauntlets",
      "Plated Crimson Defenders",
      "Sand Manipulator's Authority",
      "Einar's Padded Gauntlets",
      "Rapidcaster Mitts",
      "Lifeward Gauntlets",
      "Venomburned Gauntlets",
      "Sorcerer's Surge Grips",
      "Shinobi's Deadwraps",
      "Vigorous Lifegrips",
      "Titan's Staticguards",
      "Thorned Wristguards",
      "Demonweaver's Heralds",
      "Rakhul's Stone Hands",
      "Demonfire Accelerators",
      "Ali's Boxing Gloves",
      "Fighter Magi's Grips",
      "Necrocaller's Grips",
      "Grasp of the Phoenix",
      "Arcanum Asphyxiators",
      "Tectonic Grips",
      "Frostbitten Necrosis",
      "Manahungerers",
      "Rimskin Assassins",
      "Plague Bringer´s Touch",
      "Pit Fighter´s Bone Crushers",
      "Shade of Sand"
    ]
  },
  {
    "id": "boots",
    "sourceSection": "boots",
    "slot": "feet",
    "label": "Boots",
    "names": [
      "Boots",
      "Heavy Boots",
      "Light Plated Boots",
      "Chain Boots",
      "Greaves",
      "Battle Boots",
      "Devilhide Boots",
      "Mesh Boots",
      "Viperskin Boots",
      "War Boots",
      "Boneweave Boots",
      "Crusader Marchers",
      "Demonplate Boots",
      "Scarabshell Boots",
      "Wyrmhide Boots"
    ]
  },
  {
    "id": "boots-unique",
    "sourceSection": "boots_unique",
    "slot": "feet",
    "label": "Unique Boots",
    "names": [
      "Darkhide Boots",
      "Tundra Marchers",
      "Tribal Boots",
      "Wizard Boots",
      "Mevius' Mighty Marchers",
      "Molten Boots",
      "Frozen Marchers",
      "Zeus' Battle Boots",
      "Redneck's Working Boots",
      "Pirate Captain's Boots",
      "Death Lord's Marchers",
      "Viking's Sacred Boots",
      "Boots of Blood",
      "Hermes Boots",
      "Treasure Hunter's Boots",
      "Gladiator's Battle Sandals",
      "Dante's Boots",
      "Sacred Marchers",
      "Boots of Wild",
      "Flaming Marchers",
      "Mos'Arathim Marchers",
      "Vagabond's Marchers",
      "Bone Conjurer's Marchers",
      "Lumberjack's Forestry Boots",
      "Blood-letter's Plated Boots",
      "Shield Bearer's Greaves",
      "Juggernaut's Victory Marchers",
      "Justiciar's Thunder Boots",
      "Lost Master's Marchers",
      "Earth Shaper's Boots",
      "Plunderer's Deck Marchers",
      "Battle Worn Boots",
      "Steadfast Marchers",
      "Spiked Greaves",
      "Arena Master's Marchers",
      "Satan's Molten Steps",
      "Pearlescent Dream",
      "Mana-Woven Walkers",
      "Whisper Walker's Feiyue",
      "Voodoo Stompers",
      "Grand Wizard's Silk Shoes",
      "Lava Treaders",
      "Deep Chilled Marchers",
      "Wind Walker's Step",
      "Arch Wizard's Silk Boots",
      "Chronomancer's Omnipotence",
      "Ymir's Freezing Boots",
      "Einar's Icy Stride",
      "Grimbone's Marchers",
      "Aetherflow Treads",
      "Runescribe's Striders",
      "Pla-Yer's Choice",
      "Mos'Arathim's Kicks",
      "Stalwart Sabatons",
      "Onslaught Stompers",
      "Mystic Soles",
      "Enigma's Riftwalkers",
      "Vipermagi's Sprinters",
      "Tarek's Tradeoff",
      "Lunar Prophet's Walkers",
      "Soulflaming Marchers",
      "Arc's Walkers",
      "Marcher's of Hatred",
      "Thunder Caller's Treads",
      "Steampowered Flamewalkers",
      "DEVELOPRE BOOT",
      "Stranded Boot",
      "Rocket Boots",
      "Fumacinha´s Favela Flipflop",
      "Metal Vocalist´s War Boots",
      "Venom Roamers",
      "Thunder Roamers",
      "Chaoswalkers",
      "Chilling Roamers",
      "Scorching Roamers",
      "Astral Roamers",
      "Brutal Roamers",
      "Desert´s Storm",
      "Adamant Roamers",
      "Arc´s Walkers are powerful boots designed for leveling providing increased experience gain for characters below level 100."
    ]
  },
  {
    "id": "amulets",
    "sourceSection": "amulets",
    "slot": "headAccessory",
    "label": "Amulets",
    "names": [
      "Amulet",
      "Locket",
      "Pearls",
      "Talisman",
      "Carcanet",
      "Necklace"
    ]
  },
  {
    "id": "amulets-unique",
    "sourceSection": "amulets_unique",
    "slot": "headAccessory",
    "label": "Unique Amulets",
    "names": [
      "All Seeing Eye",
      "High Demon's Necklace",
      "Satan's Precious",
      "Shining Pearl",
      "Gurag's Pebble",
      "Anubis Oculus",
      "Tal's Pendant",
      "Damien's Soulstone",
      "Steve's Necklace",
      "Baby Log Necklace",
      "Treasure Pendant",
      "Ritual Pendant",
      "Nobunaga's Warrior Spirit",
      "Visage's Eye",
      "Elder's Heart",
      "Devil's Gem",
      "Aztec Necklace",
      "Sacred Pendant",
      "Spirit Pendant",
      "Rift Warrior's Skull",
      "Raven's Claw",
      "Eye of Horus",
      "Pyramid Pendant",
      "Storm Pendant",
      "Traveler's Compass",
      "Pendant of Eternity",
      "Juggernaut's Emblem",
      "Engineer's Master Pendant",
      "Bone Conjurer's Mask",
      "Venom's Necklace",
      "Champion's Medal of Valor",
      "Plunderer's Spy Glass",
      "Kallik's Fury",
      "Unfathomable Puzzle",
      "Philosopher's Stone",
      "Charcoal Memento",
      "Coldfire Amulet",
      "Serpentine Necklace",
      "Compass of Wealth",
      "Dark Lord's Sigil",
      "Lost Dieties Authority",
      "Thunderstone Amulet",
      "Earth Goliath's Protection",
      "Claw of the Bloodthirsty",
      "Arcana Eye",
      "Scout's Medal of Honor",
      "Claw of the Hunter",
      "Amethyst Knight's Amulet",
      "Chronomancer's Curio of Time",
      "Ymir's Frozen Tear",
      "Insignia of the Hunter",
      "Lifeblood Infuser",
      "Arcane Slayer's Talisman",
      "Rapidshell Medallion",
      "Soulreplenish Pendant",
      "Eagerblade's Tooth",
      "Coldsnap Insignia",
      "Insignia of the Burning Legion",
      "Gambler's Demise",
      "Stone of Archaeology",
      "Tarethiel's Fall",
      "Amulet of Colosseum",
      "Lilith's Scorn",
      "Arc's Sigil",
      "Light Bringer's Mark",
      "Gryphon´s Claw",
      "Eagle´s Claw",
      "Thoth´s Agony",
      "Metal Vocalist´s Pentagram",
      "Dragon´s Eye",
      "Signet of Kadosh",
      "Shadow Beacon",
      "Arc´s Sigil is a powerful amulet designed for leveling providing increased experience for characters gain below level 100."
    ]
  },
  {
    "id": "charms",
    "sourceSection": "charms",
    "slot": "backAccessory",
    "label": "Charms",
    "names": [
      "Small Charm",
      "Large Charm",
      "Grand Charm"
    ]
  },
  {
    "id": "charms-unique",
    "sourceSection": "charms_unique",
    "slot": "backAccessory",
    "label": "Unique Charms",
    "names": [
      "Raider's Torch",
      "Eye of Skadi",
      "Apple of Evolution",
      "Moonshard",
      "Solar Charm",
      "Aztec Coin",
      "Beetle of Life",
      "Tal's Deathskull",
      "Gurag's Heart Charm",
      "Anubis' Ankh Charm",
      "Damien's Cage",
      "Satan's Chalice",
      "Hello its me, Steve!",
      "Redneck's Keychain",
      "Pirate Captain's Flag",
      "Death Lord's Zombie Head",
      "Marksman's Quiver",
      "Wind Token",
      "Doctor's Mask in a Jar",
      "Heart of Agony",
      "Aztec Devil",
      "Sacred Owl",
      "Flaming Coin",
      "Torch of Shadows",
      "Traveler's Map Journal",
      "Engineer's Mini Drone",
      "Zealot's Beads of Destruction",
      "Bone Conjurer's Trophy",
      "Champion's Signet",
      "Plunderer's Gunpowder Bag",
      "Fulgurite",
      "Loaded Dice",
      "Annihilator",
      "Bag of Unknown Riches",
      "Spine Trophy",
      "Angelic Key",
      "Cold Giant's Charm",
      "Jack's Pumpkin Spice",
      "Shrunken Head",
      "Tarethiel's Ancient Wisdom",
      "Sheep King's Wool",
      "Viking's Glyphed Rune",
      "Witches Claw",
      "Adventurer's Quiver",
      "Mark of the Black Knight",
      "Hardened Steel Defender",
      "Canopic Jar of Blood",
      "Sundial of Ancient Worlds",
      "Water Melon",
      "Earth Melon",
      "Fire Melon",
      "Air Melon",
      "Supreme Elemelon",
      "Torstein's Anvil",
      "Arcane Pumpkin",
      "Rotten Pumpkin",
      "Tomtomtomtomtom",
      "Eye of Rakhul",
      "Lilith's Wrath",
      "Divine Crackpipe",
      "Abomination's Heart",
      "Abomination's Brain",
      "Abomination's Eye",
      "Plague Shot",
      "Barrel of Explosives",
      "The Detonator",
      "Gas Canister",
      "Forking Bolts",
      "Reverse Card",
      "Tablet of Awakening",
      "Crow's Feather",
      "Sassy´s Dislocated Foot",
      "Chaos Gemstone",
      "Finger of Despair",
      "Sobek´s Fall",
      "Graxy´s Mom Lure",
      "The Almighty Nugget",
      "Orange Grayon",
      "Aimbot.exe",
      "Storm In A Vial",
      "Dev Charm Small",
      "Dev Charm Large",
      "Dev Charm Grand",
      "Dragon´s Heart",
      "Wizard´s Dice",
      "Gladiator´s Dice",
      "Bob´s Grenade",
      "Cursed Gyroscope",
      "Mysterious Monkey Paw",
      "Dibbik Box",
      "Mystery Card",
      "Overloaded Dice",
      "Devil´s Pact",
      "Soul Collector",
      "Tiny Planet",
      "Telescope",
      "Nomad´s Rotten Corpse",
      "Voodoo Doll",
      "Combine the power of melons into a superior elemelon."
    ]
  },
  {
    "id": "shields",
    "sourceSection": "shields",
    "slot": "offHand",
    "label": "Shields",
    "names": [
      "Wooden Shield",
      "Buckler",
      "Steel Ward",
      "Small Crescent",
      "Aegis",
      "Kite Shield",
      "Bone Shield",
      "Luna",
      "Royal Shield",
      "Monarch",
      "Tribal Ward"
    ]
  },
  {
    "id": "shields-unique",
    "sourceSection": "shields_unique",
    "slot": "offHand",
    "label": "Unique Shields",
    "names": [
      "Ancient Aegis",
      "Tombstone",
      "Rift Eye",
      "Demon's Mirror",
      "The Templar",
      "Lancer's Wall",
      "Shadow Buckler",
      "Wall of the Legion",
      "SUOMI FINLAND PERKELE",
      "Den Glider In",
      "Gladiator's Wall",
      "Sacred Aegis",
      "Aztec Ward",
      "Ward of Toxicity",
      "Storm Gladiator's Wall",
      "Thunder Lord's Aegis",
      "Crystal Infused Shield",
      "Vagabond's Ward",
      "Flame Diviner's Ward",
      "Justiciar's Thunder Wall",
      "Shield Bearer's Wall",
      "Valkyrie's Battle Shield",
      "Leprechauns Greed",
      "Gem Encrusted Tower",
      "Pandemic Shield",
      "Iron Giants Shield",
      "St. Tomi's Vibrant Aura",
      "Defender's Justice",
      "Shield of the Abyss",
      "Mirror of Flesh",
      "St. Hallgar's Bloodforged Aegis",
      "Ward of Blood",
      "Novice's Tower",
      "King's Tower Shield",
      "Heaven's Champion",
      "Pitfiend's Thorn",
      "Celestial's Authority",
      "Visage of Relentless Rage",
      "Battle Mage's Shield",
      "Darkwood Defender",
      "Rusted Spiked Shield",
      "Blessed Defender",
      "Thunderburn Aegis",
      "Shield of Shattered Elements",
      "Battlemagi's Rampart",
      "Archmagus Glyphward",
      "Lost Wizard's Barrier",
      "Bob's Piece of Plywood",
      "Thunderstruck Deflector",
      "Rendguard of Carnage",
      "Spellbinder's Magebarrier",
      "Gabriel's Unholy Oath",
      "Pit Ravager´s Cetratus",
      "SUOMI FINLAND SUATANA",
      "Shadow Lantern"
    ]
  },
  {
    "id": "rings",
    "sourceSection": "rings",
    "slot": "eyewear",
    "label": "Rings",
    "names": [
      "Bronze Ring",
      "Iron Ring",
      "Ring",
      "Socket Ring",
      "Primal Ring",
      "Golden Ring"
    ]
  },
  {
    "id": "rings-unique",
    "sourceSection": "rings_unique",
    "slot": "eyewear",
    "label": "Unique Rings",
    "names": [
      "Ra's Band",
      "Molten Ring",
      "Dragonsteel Ring",
      "Stone of Premonition",
      "Khodo's Wedding Band",
      "Demon Eye Ring",
      "Satanic Eye",
      "Giant's Band of Strength",
      "Iron Ring of Prometheus",
      "St. Aaron's Eternal Rage",
      "Elven Grace",
      "Quickening Zephyr",
      "Mana Bender's Will",
      "Tectonic Frequency",
      "Fury of Tarethiel",
      "The Absence of Constraint",
      "Mark of Ferocity",
      "Sanguine Bloodstone",
      "Archer's Story",
      "Onyx Slayer's Band",
      "Templar's Faith",
      "Soulforged Ring",
      "Signet of Bifröst",
      "Sung Lee's Unleashed Rage",
      "Apex Striker's Ring",
      "Swiftsoul Band",
      "Soul Funneling Loop",
      "Colossus Circle of Vitality",
      "Viper's Seal of Corrosion",
      "Astrope's Signed of Blessing",
      "Ring of the Cowraven",
      "Circle of Nature",
      "Merlock's Halo",
      "Ring of Tallus",
      "Solar Prophet's Signet",
      "Lunar Prophet's Band",
      "Rakhul's Ritual Band",
      "Shackle of Insanity",
      "Destroyer’s End",
      "Signet of Harbringer",
      "Hellfire Halo",
      "Signet of Corruption",
      "Arcanis",
      "Azazel's Despair",
      "Emblem of the Daemon",
      "Stormloop",
      "Hero Siege Enjoyer",
      "Pit Fighter´s Carnage",
      "Metal Vocalist´s Fame",
      "Scourge Loop",
      "Dragon´s Blessing",
      "Cursed Artifact",
      "Signet of Shadows",
      "The Downfall of Felps",
      "Orbital Loop",
      "Hellspawn´s Curse",
      "Gargantuan´s Soul",
      "Void Bomba"
    ]
  },
  {
    "id": "belts",
    "sourceSection": "belts",
    "slot": "bodyAccessory",
    "label": "Belts",
    "names": [
      "Sash",
      "Leather Belt",
      "Heavy Belt",
      "Devilhide Sash",
      "Viperskin Belt",
      "Battle Belt",
      "Wyrmhide Sash",
      "Mithril Coil",
      "Vampirefang Girdle"
    ]
  },
  {
    "id": "belts-unique",
    "sourceSection": "belts_unique",
    "slot": "bodyAccessory",
    "label": "Unique Belts",
    "names": [
      "Tundra Warrior's Girdle",
      "Vipermagi's Belt",
      "Lich Sash",
      "Tribal Belt",
      "Foxweave Belt",
      "Assassin's Belt",
      "Crystal Belt",
      "Heavy Duty",
      "Commander's Sash",
      "Monkeyskin Belt",
      "Belt of War",
      "Traveler's Double Belt",
      "Belt of Skulls",
      "Engineer's Toolbelt",
      "Vagabond's Strap",
      "Flame Diviner's Cord",
      "Justiciar's Thunder Sash",
      "Earth Shaper's Belt",
      "Knight's Girdle",
      "Belt of Infinite Wealth",
      "Rugal's Sash of Undertaking",
      "Sash of the Magi",
      "Ice Queen's Cestus",
      "Set's Lightning Sash",
      "Tether of Anguish",
      "Hatshepsut's Girdle",
      "Ashen Belt",
      "Combat Duty Belt",
      "Cingulum of Shifting Destiny",
      "Brute's Cord",
      "Sun Wukong's Belt",
      "Warbosses' Trophy Belt",
      "Gaze of the Void",
      "Pitfighter's Razor Belt",
      "Bronze Legion Girdle",
      "Girdle of Resilience",
      "USB's Cord",
      "Guardian's Waistband",
      "Storm's Dawn",
      "Runemaster's Waistwrap",
      "Solar Magister's Sash",
      "Lunar Prophet's Girdle",
      "Sash of Eternal Hatred",
      "Gladiator King's Belt",
      "Majorie's Belt",
      "Butcher's Belt",
      "Thunder Caller's Sash",
      "Soulburn Belt",
      "Freya's Frozen Buckle",
      "Komodo’s Bloodstrap",
      "Trophy Hunter",
      "Liquor Holster",
      "Girdle of Eternal War",
      "El Patrón´s Madness",
      "Sandmagi´s Sash"
    ]
  }
] as const satisfies readonly HeroSiegeItemCategory[];

export const HERO_SIEGE_ITEM_NAMES_BY_SLOT: Record<Exclude<EquipmentSlot, "ringTwo">, string[]> = {
  "mainHand": [
    "Hand Axe",
    "Hatchet",
    "Naga",
    "Broad Axe",
    "War Axe",
    "Giant Axe",
    "Cudgel",
    "Mace",
    "Morning Star",
    "Spiked Club",
    "War Hammer",
    "Maul",
    "Ogre Maul",
    "Martel De Fer",
    "Flail",
    "Devil Star",
    "Dagger",
    "Dirge",
    "Kris",
    "Short Sword",
    "Sabre",
    "Claymore",
    "Broad Sword",
    "Scimitar",
    "Giant Sword",
    "Katana",
    "War Sword",
    "Falchion",
    "Flamberge",
    "Zangetsu",
    "Godfather",
    "Jade Warrior's Gladius",
    "Storm Katana",
    "Molten Sword",
    "Inferno Slayer",
    "Dragon Knight's Flail",
    "Rift Commander's Axe",
    "The Undying",
    "Shattered Dimensions",
    "Ashbringer",
    "Death's Mirror",
    "Odin's Battle Axe",
    "Gurag's Stone Crusher",
    "Death's Scythe",
    "Hiyoki's Vorpal Katana",
    "Hanzo's Flaming Katana",
    "Genji's Sword of Fate",
    "Wind Guardian's Gladius",
    "Sand Crusader's Scimitar",
    "Azure's Wrath",
    "Holy Warrior's Phase Blade",
    "Steve's Mighty Sword",
    "St. Gabriel's Retribution",
    "Thor's Battle Sword",
    "Viking's Sacred Axe",
    "Nomad's Sandslicer",
    "Nobunaga's Battle Slicer",
    "Molten Dagger",
    "Icy Shank",
    "Darkness",
    "Gladiator's Wrecking Ball",
    "Dante's Demon Blade",
    "Shadow Carver",
    "Sacred Whip",
    "Nightmare Slasher",
    "Frozen Carver",
    "Unholy God's Flail",
    "Molten Hammer",
    "Icy Crusher",
    "The Light of Dawn",
    "Gladiator's Skullcrusher",
    "Masamune",
    "Muramasa",
    "Crystal Infused Axe",
    "Crystal Infused Sword",
    "Sung Lee's Destroyer Flail",
    "Revenant's Lasher",
    "Bonetti's Rapier",
    "Eternal Glaive",
    "Gut's BFS",
    "St. Rexis Sundering Axe",
    "Sand Dagger",
    "Thunder Dagger",
    "Riftmaster's Dirge",
    "St. Mika's Zweihänder",
    "Sanguine Blade",
    "Pillar of Niflheim",
    "Grimbone's Scythe",
    "Ceremonial Dagger",
    "Spiritus",
    "Gut's HFS",
    "Sähköpuimuri",
    "Arch Angel's Phase Blade",
    "Gem King's Cleaver",
    "Winter's Bite",
    "Wraith Forged Cleaver",
    "Aurelion Fury",
    "Abomination's Gut Ripper",
    "Rakhul's Legion Crusher",
    "Daisy",
    "The Dawn Bringer",
    "Gabriel's Broken Resolve",
    "The Hope Ender",
    "Luci's Day",
    "Glowstick Estoc",
    "Headsman´s Bloodthirster",
    "Shishkebab",
    "Stormslayer",
    "Blood Moon Crescent",
    "Stofflix Cooking Cleaver",
    "Doom Cutter",
    "Pit Fighter´s Skullcracker",
    "Pit Fighter´s Brutalizer",
    "Metal Vocalist´s Warlock",
    "Fenrir´s Bloodfang",
    "Throwing Axe",
    "Battle Darts",
    "Throwing Disc",
    "Harpoon",
    "Javelin",
    "Pilum",
    "Simbilan",
    "Short Spear",
    "Throwing Spear",
    "Mimir's Corrupted Axe",
    "Scarred Battle Darts",
    "Wakayka's Tomahawk",
    "Imperial Glaive",
    "Ukko's Revenge",
    "Wargod's Wrath",
    "St. Neri's Rainbow Lance",
    "Serpent's Tooth",
    "Crystal Infused Javelin",
    "Valkyrie's Thunder Javelin",
    "Deep Sea Glaive",
    "Sowyer's Javelin of Devastation",
    "Sidewinder",
    "Gnarled Staff",
    "Cane",
    "Arcane Fork",
    "Spellblade",
    "Wand",
    "Magic Tome",
    "Yew Wand",
    "Spellshard",
    "The Iris",
    "Staff of Nether Flame",
    "Archangel Staff",
    "Oculus of Ages",
    "God's Benevolence",
    "Satan's Unholy Bible",
    "Book of Revelations",
    "Damien's Head",
    "Clafaxier",
    "Raise of the Dead",
    "Dragon's Breath",
    "Apocalypto",
    "Steve's Wand of Fortune",
    "St. HouDeanii's Tiny Fire Rod",
    "Wormclaw",
    "Beacon of Shadows",
    "Crystal Infused Wand",
    "Zealot's Book of Prophecy",
    "Uabel's Wand",
    "Battle Mage's Wand",
    "Spell Eater",
    "Blood of Abaddon",
    "Ancient Sun Beacon",
    "The Eye of Tarethiel",
    "Sands of Time",
    "Crystal Cane of Ice",
    "Cane of the Tundra",
    "Book of Cold Death",
    "Thorn of Helheim",
    "Flame of the Phoenix",
    "Hypothermia",
    "St. Nimo's Lightbringer",
    "Solar Prophet's Tablet",
    "Pagan God's Blasphemy",
    "Voodoo Magician's Skull",
    "Wraithbone",
    "Clafaxier's Legacy",
    "Manafunneler´s Conjurer",
    "Crackling Thunder",
    "Necrobutcher´s Curse",
    "Crow´s Whisper",
    "Damien´s Corrupted Head",
    "Witch´s Wand",
    "Crossbow",
    "Short War Bow",
    "Long Bow",
    "Gothic Bow",
    "Buriza-ko-nu",
    "Wind's Force",
    "Poison Ivy",
    "Glimmerfury",
    "Flamebringer",
    "Steve's Punchbow",
    "St. Soloyolo's Holy Bow",
    "Marksman's Hunting Bow",
    "Shadowfury",
    "Electro",
    "Hellspawn Eradicator",
    "Deathquill",
    "Recurving Corrosion",
    "St. Amitiel's Truth",
    "Astral Projector",
    "Arachno Phobia",
    "Monsoon",
    "Arrow of Niflheim",
    "Eternity",
    "Arrow of Zamjo",
    "Wrist Blades",
    "Blade Talons",
    "Feral Claws",
    "Storm Fury",
    "Molten Paw",
    "Hemorrhage",
    "Yoshi's Throat-Cutters",
    "Elemental Claws",
    "Talons of Wisdom",
    "Earth Shaper's Talons",
    "Spirit Walker's Guide",
    "Glacier Talons",
    "Spear",
    "Tribal Spear",
    "Royal Lance",
    "War Trident",
    "Battle Lance",
    "Hyperion Spear",
    "Yari",
    "Fuscina",
    "War Spear",
    "Crusader Halberd",
    "Poseidon's Might",
    "Odin's Battle Spear",
    "Vanguard's Lance",
    "War God's Lance",
    "Jousting Lance",
    "Golden God's Gladius",
    "St. Draxis' Pigstick",
    "Lancer's Glory",
    "Champion's Flag Lance",
    "Dark Knight's Lance",
    "Brimskull Trident",
    "Thorn of Noxus",
    "Hand Cannon",
    "Hunting Rifle",
    "Gatling Gun",
    "Battle Blaster",
    "RT XQC-4910",
    "Vampire Hunter",
    "Flamecannon",
    "Warbringer",
    "Jack",
    "Fred",
    "Steve's Bang",
    "Chills of War",
    "Commander´s Sentry Blaster",
    "Marine's Buddy",
    "Demon",
    "Angel",
    "Crystal Infused Pistol",
    "F4-Tactical Rifle",
    "Dreadnought",
    "AK-47",
    "Glock 22",
    "Dracula´s Demise",
    "Battle Slicer",
    "War Saw",
    "Trunk Cutter",
    "Hand Saw",
    "Sawgun",
    "Doublesaw 4000",
    "Doomsaw",
    "Vorpal Sharktooth",
    "The Annihilator",
    "St. Draxis Longsaw",
    "Lumberjack's Chainsaw",
    "Candy Shredder",
    "Royal Decapitator",
    "Diablo",
    "Eden´s Harvester",
    "Poison Flask",
    "Caustic Vial",
    "Acid Flask",
    "Alchemist's Flask",
    "Cobra Blood Vial",
    "Ancient Mucus",
    "Demon Blood Flask",
    "Spirit Urn",
    "Doctor's Potion",
    "Doomweed Vial",
    "Lemon",
    "Fishing Rod",
    "Voided Item"
  ],
  "offHand": [
    "Wooden Shield",
    "Buckler",
    "Steel Ward",
    "Small Crescent",
    "Aegis",
    "Kite Shield",
    "Bone Shield",
    "Luna",
    "Royal Shield",
    "Monarch",
    "Tribal Ward",
    "Ancient Aegis",
    "Tombstone",
    "Rift Eye",
    "Demon's Mirror",
    "The Templar",
    "Lancer's Wall",
    "Shadow Buckler",
    "Wall of the Legion",
    "SUOMI FINLAND PERKELE",
    "Den Glider In",
    "Gladiator's Wall",
    "Sacred Aegis",
    "Aztec Ward",
    "Ward of Toxicity",
    "Storm Gladiator's Wall",
    "Thunder Lord's Aegis",
    "Crystal Infused Shield",
    "Vagabond's Ward",
    "Flame Diviner's Ward",
    "Justiciar's Thunder Wall",
    "Shield Bearer's Wall",
    "Valkyrie's Battle Shield",
    "Leprechauns Greed",
    "Gem Encrusted Tower",
    "Pandemic Shield",
    "Iron Giants Shield",
    "St. Tomi's Vibrant Aura",
    "Defender's Justice",
    "Shield of the Abyss",
    "Mirror of Flesh",
    "St. Hallgar's Bloodforged Aegis",
    "Ward of Blood",
    "Novice's Tower",
    "King's Tower Shield",
    "Heaven's Champion",
    "Pitfiend's Thorn",
    "Celestial's Authority",
    "Visage of Relentless Rage",
    "Battle Mage's Shield",
    "Darkwood Defender",
    "Rusted Spiked Shield",
    "Blessed Defender",
    "Thunderburn Aegis",
    "Shield of Shattered Elements",
    "Battlemagi's Rampart",
    "Archmagus Glyphward",
    "Lost Wizard's Barrier",
    "Bob's Piece of Plywood",
    "Thunderstruck Deflector",
    "Rendguard of Carnage",
    "Spellbinder's Magebarrier",
    "Gabriel's Unholy Oath",
    "Pit Ravager´s Cetratus",
    "SUOMI FINLAND SUATANA",
    "Shadow Lantern"
  ],
  "headgear": [
    "Cap",
    "Casque",
    "Basinet",
    "War Hat",
    "Great Helm",
    "War Visage",
    "Shako",
    "Horned Helm",
    "Basilisk Skull",
    "Harlequinn's Crest",
    "Harlequinn's Veil",
    "The Colossal Avenger",
    "Demon Warlord's Helm",
    "The Bucket",
    "Sky Crusader Helm",
    "Helm of Dominator",
    "The Faceless Priest",
    "Uabel's Helmet",
    "Reaper's Hood",
    "Genji's Battle Helmet",
    "Mevius' Mighty Helmet",
    "Flame God's Helmet",
    "Ice King's Crown",
    "Zeus' Circlet",
    "Redneck's Cap",
    "Pirate Captain's Hat",
    "Death Lord's Crown",
    "Thor's Battle Cap",
    "Viking's Sacred Helmet",
    "Nomad's Sand Bandana",
    "Nobunaga's Battle Helmet",
    "Gladiator's Skullet",
    "Doctor's Visage",
    "Aztec Crown",
    "Wendigo Skull",
    "Judge, Jury & Executioner",
    "Death Knight's Visage",
    "Ancient Avenger",
    "Burning Gaze",
    "Sight Of The Gods",
    "Zealot's Guise of Doom",
    "Flame Diviner's Refuge",
    "Lumberjack's Safety Helm",
    "Blood-letter's Crown",
    "Venom's Skull",
    "Shield Bearer's Crown",
    "Juggernaut's Siege Helm",
    "Lost Master's Vision",
    "Valkyrie's Winged Helm",
    "Surgical Mask",
    "Battle Worn Visor",
    "Underworld's Skullbreaker",
    "Sand Traveler's Guise",
    "Crown of the Holy One",
    "Guise of the Dead",
    "Veil of Mystery",
    "Crown of the North",
    "Tenebris' Grievance",
    "Mask of the Beyond",
    "Pit Lord's Vanquisher",
    "Lava King's Lost Mask",
    "The Grand Champion",
    "Crown of Midnight",
    "Nikita's KJ-33 Helmet",
    "The Curator of Secrets",
    "Sheep King's Crown",
    "Warlord's Fury",
    "Witches Brimmed Hat",
    "Assassin's Hood",
    "Knight Captain's Helmet",
    "Chronomancer's Observance",
    "Sand Manipulator's Mask",
    "Ymir's Frozen Shroud",
    "Einar's Horned Helmet",
    "Gabriel's Brimmed Fedora",
    "Grimbone's Visage",
    "Odin's Eternal Visage",
    "Aetherweaver's Veil",
    "Sentinel's Headguard",
    "Executioner's Headplate",
    "Bloodthirster's Warhelm",
    "Mage's Starshroud",
    "Reaver's Headplate",
    "Juda's Broken Halo",
    "Solar Prophet's Crown",
    "Lunar Prophet's Tiara",
    "Butcher's Hood",
    "Gabriel's Dauntless Vision",
    "Thunder Caller's Veil",
    "High Roller´s Deathcrown",
    "Gaze of the Oblivion",
    "Eternal Death",
    "Metal Vocalist´s Leather Mask",
    "Dragon Knight´s Helmet",
    "Crown of Doom",
    "Lucifer´s Crown",
    "Mask of the Celestial",
    "Veil of Consecration"
  ],
  "armor": [
    "Steel Armor",
    "Leather Coat",
    "Studded Leather",
    "Trellised Armor",
    "Breast Plate",
    "Cuirass",
    "Templar Coat",
    "Wire Fleece",
    "Boneweave",
    "Chaos Armor",
    "Dusk Shroud",
    "Great Hauberk",
    "Heaven's Might",
    "Leviathan's Carcass",
    "Tayrel's Chestplate",
    "Uabel's Chest",
    "Marsh Shroud",
    "Gladiator's Demise",
    "Hellfire Cuirass",
    "Devil's Cocoon",
    "Mevius' Mighty Plate",
    "Anubis Torso",
    "Genji's Battle Armor",
    "Satan's Cuirass",
    "Sand King's Scarab",
    "Ice Howl's Cuirass",
    "Grandwizard's Robe",
    "Zeus' Body Armor",
    "Redneck's Shirt",
    "Pirate Captain's Shirt",
    "Death Lord's Bone Armor",
    "Thor's Chest Armor",
    "Cuirass of Blood",
    "Magister's Robe",
    "Nomad's Battlerobe",
    "Marksman's Hunting Shroud",
    "Upi's Sweetshirt",
    "Thunder Gladiator's Armor",
    "Nobunaga's Battle Cuirass",
    "Dante's Jacket",
    "Lancer's Chestplate",
    "Demon's Ribcage",
    "Sacred Robe",
    "Chestplate of Fire",
    "Lichbane",
    "St. Jupe's Plate of Command",
    "Traveler's Leather Jacket",
    "Gem King's Garb",
    "Engineer's Plated Vest",
    "Vagabond's Wraps",
    "Flame Diviner's Sanctum",
    "Blood-letter's Plate Body",
    "Venom's Ribcage",
    "Shield Bearer's Plated Armor",
    "Juggernaut's Glorious Plate",
    "Justiciar's Thunder Armor",
    "Lost Master's Platemail",
    "Earth Shaper's body",
    "Plunderer's Jacket",
    "Valkyrie's Battle Raiment",
    "Hazmat Suit",
    "Molten Steel Cataphract",
    "Tropical Storm",
    "Magic-Imbued Frozen Plate",
    "Zephy's Gown",
    "Mystique Allure",
    "Cocoon of the Berserker",
    "Giant Thorned Lizard Skin",
    "Noxious Hunter's Reward",
    "Empire's Military Plate",
    "Leather Muscle Breastplate",
    "Tundra Hunter's Long Coat",
    "Arcane Robes of Authority",
    "Thunder Guardian's Plate",
    "Tactical Flak Jacket",
    "Unearthed Esoteric Panoply",
    "Sheep King's Hide",
    "Clan Leader's Pride",
    "Elementalist's Silk Shroud",
    "Bandit Lord's Shroud",
    "Black Knight's Carapace",
    "Behemoth's Damascus Body",
    "Sand Manipulator's Kalasiris",
    "Ymir's Frozen Vestment",
    "Einar's Plated Armor",
    "Gabriel's Leather Trench Coat",
    "Grimbone's Ribcage",
    "Odin's Battlearmor",
    "Ironclad Protector",
    "Magiward Battlegear",
    "Wardbreaker Armor",
    "Aegisweave Robes",
    "Solar Prophet's Robes",
    "Stoneplate of Corruption",
    "Butcher's Apron",
    "Gabriel's Broken Wings",
    "Thunder Caller's Robe",
    "Muspelheim Guardian's Scorched Plate",
    "Venomsteel Carapace",
    "Isarius Ironthorn Breastplate",
    "Executioner's Cocoon",
    "Exiled Pagan´s Mantle",
    "Runemaster´s Mantle",
    "Glacial Gladiator´s Armor",
    "Magma Gladiator´s Armor",
    "Scourge Gladiator´s Armor",
    "Arcane Gladiator´s Armor",
    "Grand Arch Wizard´s Mantle",
    "Pit Fighter´s Band Shirt",
    "Dragon Knight´s Vanguard",
    "Wraith´s Cloak",
    "Arcanist´s Wrath",
    "Sharpshooter´s Cloak"
  ],
  "headAccessory": [
    "Amulet",
    "Locket",
    "Pearls",
    "Talisman",
    "Carcanet",
    "Necklace",
    "All Seeing Eye",
    "High Demon's Necklace",
    "Satan's Precious",
    "Shining Pearl",
    "Gurag's Pebble",
    "Anubis Oculus",
    "Tal's Pendant",
    "Damien's Soulstone",
    "Steve's Necklace",
    "Baby Log Necklace",
    "Treasure Pendant",
    "Ritual Pendant",
    "Nobunaga's Warrior Spirit",
    "Visage's Eye",
    "Elder's Heart",
    "Devil's Gem",
    "Aztec Necklace",
    "Sacred Pendant",
    "Spirit Pendant",
    "Rift Warrior's Skull",
    "Raven's Claw",
    "Eye of Horus",
    "Pyramid Pendant",
    "Storm Pendant",
    "Traveler's Compass",
    "Pendant of Eternity",
    "Juggernaut's Emblem",
    "Engineer's Master Pendant",
    "Bone Conjurer's Mask",
    "Venom's Necklace",
    "Champion's Medal of Valor",
    "Plunderer's Spy Glass",
    "Kallik's Fury",
    "Unfathomable Puzzle",
    "Philosopher's Stone",
    "Charcoal Memento",
    "Coldfire Amulet",
    "Serpentine Necklace",
    "Compass of Wealth",
    "Dark Lord's Sigil",
    "Lost Dieties Authority",
    "Thunderstone Amulet",
    "Earth Goliath's Protection",
    "Claw of the Bloodthirsty",
    "Arcana Eye",
    "Scout's Medal of Honor",
    "Claw of the Hunter",
    "Amethyst Knight's Amulet",
    "Chronomancer's Curio of Time",
    "Ymir's Frozen Tear",
    "Insignia of the Hunter",
    "Lifeblood Infuser",
    "Arcane Slayer's Talisman",
    "Rapidshell Medallion",
    "Soulreplenish Pendant",
    "Eagerblade's Tooth",
    "Coldsnap Insignia",
    "Insignia of the Burning Legion",
    "Gambler's Demise",
    "Stone of Archaeology",
    "Tarethiel's Fall",
    "Amulet of Colosseum",
    "Lilith's Scorn",
    "Arc's Sigil",
    "Light Bringer's Mark",
    "Gryphon´s Claw",
    "Eagle´s Claw",
    "Thoth´s Agony",
    "Metal Vocalist´s Pentagram",
    "Dragon´s Eye",
    "Signet of Kadosh",
    "Shadow Beacon",
    "Arc´s Sigil is a powerful amulet designed for leveling providing increased experience for characters gain below level 100."
  ],
  "eyewear": [
    "Bronze Ring",
    "Iron Ring",
    "Ring",
    "Socket Ring",
    "Primal Ring",
    "Golden Ring",
    "Ra's Band",
    "Molten Ring",
    "Dragonsteel Ring",
    "Stone of Premonition",
    "Khodo's Wedding Band",
    "Demon Eye Ring",
    "Satanic Eye",
    "Giant's Band of Strength",
    "Iron Ring of Prometheus",
    "St. Aaron's Eternal Rage",
    "Elven Grace",
    "Quickening Zephyr",
    "Mana Bender's Will",
    "Tectonic Frequency",
    "Fury of Tarethiel",
    "The Absence of Constraint",
    "Mark of Ferocity",
    "Sanguine Bloodstone",
    "Archer's Story",
    "Onyx Slayer's Band",
    "Templar's Faith",
    "Soulforged Ring",
    "Signet of Bifröst",
    "Sung Lee's Unleashed Rage",
    "Apex Striker's Ring",
    "Swiftsoul Band",
    "Soul Funneling Loop",
    "Colossus Circle of Vitality",
    "Viper's Seal of Corrosion",
    "Astrope's Signed of Blessing",
    "Ring of the Cowraven",
    "Circle of Nature",
    "Merlock's Halo",
    "Ring of Tallus",
    "Solar Prophet's Signet",
    "Lunar Prophet's Band",
    "Rakhul's Ritual Band",
    "Shackle of Insanity",
    "Destroyer’s End",
    "Signet of Harbringer",
    "Hellfire Halo",
    "Signet of Corruption",
    "Arcanis",
    "Azazel's Despair",
    "Emblem of the Daemon",
    "Stormloop",
    "Hero Siege Enjoyer",
    "Pit Fighter´s Carnage",
    "Metal Vocalist´s Fame",
    "Scourge Loop",
    "Dragon´s Blessing",
    "Cursed Artifact",
    "Signet of Shadows",
    "The Downfall of Felps",
    "Orbital Loop",
    "Hellspawn´s Curse",
    "Gargantuan´s Soul",
    "Void Bomba"
  ],
  "bodyAccessory": [
    "Heavy Gloves",
    "Chain Gloves",
    "Gauntlets",
    "Leather Gloves",
    "Snakeskin Gloves",
    "Heavy Bracers",
    "War Gauntlets",
    "Devilhide Gloves",
    "Vampirebone Gloves",
    "Demonbraces",
    "Ogre Gauntlets",
    "Archmage Wraps",
    "Shadow's Grasp",
    "Midas' Hands",
    "Scuttle Crab Gauntlets",
    "Warmaster's Tribal Paws",
    "Death's Grasp",
    "Anubis' Mighty Hands",
    "Mevius' Mighty Gauntlets",
    "Throat Cutters",
    "Thor's Battle Gloves",
    "Nomad's Sand Mitts",
    "Marksman's Hunting Gloves",
    "Doctor's Grasp",
    "Dante's Mitts",
    "Lancers Gauntlets",
    "Devil's Grasp",
    "Gloves of Wilderness",
    "Hands of Flame",
    "Conjurer Mitts",
    "Zealot's Deathbringers",
    "Bone Conjurer's Grips",
    "Lumberjack's Safety Gloves",
    "Blood-letter's Plated Gauntlet",
    "Venom's Talons",
    "Champion's Fighting Gloves",
    "Lost Master's Gauntlets",
    "Brawler's Fighting Mitts",
    "Shadow Occultist's Wraps",
    "Razor Knuckles",
    "Siege Breakers",
    "Spellweavers",
    "St. Ahto's Diamond Hands",
    "Uabel's Gloves",
    "Battle Worn Gauntlets",
    "Wisdom's Hold",
    "Imbued Mage Gloves",
    "Battle Caster's Gauntlets",
    "Plated Crimson Defenders",
    "Sand Manipulator's Authority",
    "Einar's Padded Gauntlets",
    "Rapidcaster Mitts",
    "Lifeward Gauntlets",
    "Venomburned Gauntlets",
    "Sorcerer's Surge Grips",
    "Shinobi's Deadwraps",
    "Vigorous Lifegrips",
    "Titan's Staticguards",
    "Thorned Wristguards",
    "Demonweaver's Heralds",
    "Rakhul's Stone Hands",
    "Demonfire Accelerators",
    "Ali's Boxing Gloves",
    "Fighter Magi's Grips",
    "Necrocaller's Grips",
    "Grasp of the Phoenix",
    "Arcanum Asphyxiators",
    "Tectonic Grips",
    "Frostbitten Necrosis",
    "Manahungerers",
    "Rimskin Assassins",
    "Plague Bringer´s Touch",
    "Pit Fighter´s Bone Crushers",
    "Shade of Sand",
    "Sash",
    "Leather Belt",
    "Heavy Belt",
    "Devilhide Sash",
    "Viperskin Belt",
    "Battle Belt",
    "Wyrmhide Sash",
    "Mithril Coil",
    "Vampirefang Girdle",
    "Tundra Warrior's Girdle",
    "Vipermagi's Belt",
    "Lich Sash",
    "Tribal Belt",
    "Foxweave Belt",
    "Assassin's Belt",
    "Crystal Belt",
    "Heavy Duty",
    "Commander's Sash",
    "Monkeyskin Belt",
    "Belt of War",
    "Traveler's Double Belt",
    "Belt of Skulls",
    "Engineer's Toolbelt",
    "Vagabond's Strap",
    "Flame Diviner's Cord",
    "Justiciar's Thunder Sash",
    "Earth Shaper's Belt",
    "Knight's Girdle",
    "Belt of Infinite Wealth",
    "Rugal's Sash of Undertaking",
    "Sash of the Magi",
    "Ice Queen's Cestus",
    "Set's Lightning Sash",
    "Tether of Anguish",
    "Hatshepsut's Girdle",
    "Ashen Belt",
    "Combat Duty Belt",
    "Cingulum of Shifting Destiny",
    "Brute's Cord",
    "Sun Wukong's Belt",
    "Warbosses' Trophy Belt",
    "Gaze of the Void",
    "Pitfighter's Razor Belt",
    "Bronze Legion Girdle",
    "Girdle of Resilience",
    "USB's Cord",
    "Guardian's Waistband",
    "Storm's Dawn",
    "Runemaster's Waistwrap",
    "Solar Magister's Sash",
    "Lunar Prophet's Girdle",
    "Sash of Eternal Hatred",
    "Gladiator King's Belt",
    "Majorie's Belt",
    "Butcher's Belt",
    "Thunder Caller's Sash",
    "Soulburn Belt",
    "Freya's Frozen Buckle",
    "Komodo’s Bloodstrap",
    "Trophy Hunter",
    "Liquor Holster",
    "Girdle of Eternal War",
    "El Patrón´s Madness",
    "Sandmagi´s Sash"
  ],
  "backAccessory": [
    "Small Charm",
    "Large Charm",
    "Grand Charm",
    "Raider's Torch",
    "Eye of Skadi",
    "Apple of Evolution",
    "Moonshard",
    "Solar Charm",
    "Aztec Coin",
    "Beetle of Life",
    "Tal's Deathskull",
    "Gurag's Heart Charm",
    "Anubis' Ankh Charm",
    "Damien's Cage",
    "Satan's Chalice",
    "Hello its me, Steve!",
    "Redneck's Keychain",
    "Pirate Captain's Flag",
    "Death Lord's Zombie Head",
    "Marksman's Quiver",
    "Wind Token",
    "Doctor's Mask in a Jar",
    "Heart of Agony",
    "Aztec Devil",
    "Sacred Owl",
    "Flaming Coin",
    "Torch of Shadows",
    "Traveler's Map Journal",
    "Engineer's Mini Drone",
    "Zealot's Beads of Destruction",
    "Bone Conjurer's Trophy",
    "Champion's Signet",
    "Plunderer's Gunpowder Bag",
    "Fulgurite",
    "Loaded Dice",
    "Annihilator",
    "Bag of Unknown Riches",
    "Spine Trophy",
    "Angelic Key",
    "Cold Giant's Charm",
    "Jack's Pumpkin Spice",
    "Shrunken Head",
    "Tarethiel's Ancient Wisdom",
    "Sheep King's Wool",
    "Viking's Glyphed Rune",
    "Witches Claw",
    "Adventurer's Quiver",
    "Mark of the Black Knight",
    "Hardened Steel Defender",
    "Canopic Jar of Blood",
    "Sundial of Ancient Worlds",
    "Water Melon",
    "Earth Melon",
    "Fire Melon",
    "Air Melon",
    "Supreme Elemelon",
    "Torstein's Anvil",
    "Arcane Pumpkin",
    "Rotten Pumpkin",
    "Tomtomtomtomtom",
    "Eye of Rakhul",
    "Lilith's Wrath",
    "Divine Crackpipe",
    "Abomination's Heart",
    "Abomination's Brain",
    "Abomination's Eye",
    "Plague Shot",
    "Barrel of Explosives",
    "The Detonator",
    "Gas Canister",
    "Forking Bolts",
    "Reverse Card",
    "Tablet of Awakening",
    "Crow's Feather",
    "Sassy´s Dislocated Foot",
    "Chaos Gemstone",
    "Finger of Despair",
    "Sobek´s Fall",
    "Graxy´s Mom Lure",
    "The Almighty Nugget",
    "Orange Grayon",
    "Aimbot.exe",
    "Storm In A Vial",
    "Dev Charm Small",
    "Dev Charm Large",
    "Dev Charm Grand",
    "Dragon´s Heart",
    "Wizard´s Dice",
    "Gladiator´s Dice",
    "Bob´s Grenade",
    "Cursed Gyroscope",
    "Mysterious Monkey Paw",
    "Dibbik Box",
    "Mystery Card",
    "Overloaded Dice",
    "Devil´s Pact",
    "Soul Collector",
    "Tiny Planet",
    "Telescope",
    "Nomad´s Rotten Corpse",
    "Voodoo Doll",
    "Combine the power of melons into a superior elemelon."
  ],
  "feet": [
    "Boots",
    "Heavy Boots",
    "Light Plated Boots",
    "Chain Boots",
    "Greaves",
    "Battle Boots",
    "Devilhide Boots",
    "Mesh Boots",
    "Viperskin Boots",
    "War Boots",
    "Boneweave Boots",
    "Crusader Marchers",
    "Demonplate Boots",
    "Scarabshell Boots",
    "Wyrmhide Boots",
    "Darkhide Boots",
    "Tundra Marchers",
    "Tribal Boots",
    "Wizard Boots",
    "Mevius' Mighty Marchers",
    "Molten Boots",
    "Frozen Marchers",
    "Zeus' Battle Boots",
    "Redneck's Working Boots",
    "Pirate Captain's Boots",
    "Death Lord's Marchers",
    "Viking's Sacred Boots",
    "Boots of Blood",
    "Hermes Boots",
    "Treasure Hunter's Boots",
    "Gladiator's Battle Sandals",
    "Dante's Boots",
    "Sacred Marchers",
    "Boots of Wild",
    "Flaming Marchers",
    "Mos'Arathim Marchers",
    "Vagabond's Marchers",
    "Bone Conjurer's Marchers",
    "Lumberjack's Forestry Boots",
    "Blood-letter's Plated Boots",
    "Shield Bearer's Greaves",
    "Juggernaut's Victory Marchers",
    "Justiciar's Thunder Boots",
    "Lost Master's Marchers",
    "Earth Shaper's Boots",
    "Plunderer's Deck Marchers",
    "Battle Worn Boots",
    "Steadfast Marchers",
    "Spiked Greaves",
    "Arena Master's Marchers",
    "Satan's Molten Steps",
    "Pearlescent Dream",
    "Mana-Woven Walkers",
    "Whisper Walker's Feiyue",
    "Voodoo Stompers",
    "Grand Wizard's Silk Shoes",
    "Lava Treaders",
    "Deep Chilled Marchers",
    "Wind Walker's Step",
    "Arch Wizard's Silk Boots",
    "Chronomancer's Omnipotence",
    "Ymir's Freezing Boots",
    "Einar's Icy Stride",
    "Grimbone's Marchers",
    "Aetherflow Treads",
    "Runescribe's Striders",
    "Pla-Yer's Choice",
    "Mos'Arathim's Kicks",
    "Stalwart Sabatons",
    "Onslaught Stompers",
    "Mystic Soles",
    "Enigma's Riftwalkers",
    "Vipermagi's Sprinters",
    "Tarek's Tradeoff",
    "Lunar Prophet's Walkers",
    "Soulflaming Marchers",
    "Arc's Walkers",
    "Marcher's of Hatred",
    "Thunder Caller's Treads",
    "Steampowered Flamewalkers",
    "DEVELOPRE BOOT",
    "Stranded Boot",
    "Rocket Boots",
    "Fumacinha´s Favela Flipflop",
    "Metal Vocalist´s War Boots",
    "Venom Roamers",
    "Thunder Roamers",
    "Chaoswalkers",
    "Chilling Roamers",
    "Scorching Roamers",
    "Astral Roamers",
    "Brutal Roamers",
    "Desert´s Storm",
    "Adamant Roamers",
    "Arc´s Walkers are powerful boots designed for leveling providing increased experience gain for characters below level 100."
  ]
};

export const HERO_SIEGE_ITEM_CATEGORY_COUNT = HERO_SIEGE_ITEM_CATEGORIES.length;
export const HERO_SIEGE_ITEM_SOURCE_NAME_COUNT = 1051;
export const HERO_SIEGE_ITEM_NAME_COUNT = 1051;
