import type { ItemModifierKey } from "../types/study";

const plus = (value: number) => value > 0 ? `+${value}` : `${value}`;
const lower = (value: number) => value > 0 ? `-${value}` : `+${Math.abs(value)}`;

export const MODIFIER_FORMATTERS: Partial<Record<ItemModifierKey, (value: number) => string>> = {
  accuracyPercent: (value) => `${plus(value)}% Attack Rating`,
  armor: (value) => `${plus(value)} Armor`,
  armorPenetrationPercent: (value) => `${plus(value)}% Armor Penetration`,
  blockChancePercent: (value) => `${plus(value)}% Block Chance`,
  blockFirstHit: (value) => value > 0 ? "Blocks the first hit in each room" : "",
  bonusDamageVsElitesPercent: (value) => `${plus(value)}% Damage to Elites`,
  bonusDamageWhileFullHealthPercent: (value) => `${plus(value)}% Damage at Full Life`,
  bonusDamageWhileLowHealthPercent: (value) => `${plus(value)}% Damage While Wounded`,
  bonusXpPercent: (value) => `${plus(value)}% Experience Gained`,
  coldDamage: (value) => `${plus(value)} Cold Damage`,
  coldResistPercent: (value) => `${plus(value)}% Cold Resistance`,
  criticalChancePercent: (value) => `${plus(value)}% Critical Strike Chance`,
  criticalDamagePercent: (value) => `${plus(value)}% Critical Strike Damage`,
  damageReduction: (value) => `${lower(value)} Damage Taken`,
  dodgeChancePercent: (value) => `${plus(value)}% Dodge Chance`,
  eliteDropBonusPercent: (value) => `${plus(value)}% Elite Reward Chance`,
  enhancedDamagePercent: (value) => `${plus(value)}% Enhanced Damage`,
  executeChancePercent: (value) => `${plus(value)}% Execute Chance`,
  extraAttackChancePercent: (value) => `${plus(value)}% Chance for an Extra Hit`,
  fireDamage: (value) => `${plus(value)} Fire Damage`,
  fireResistPercent: (value) => `${plus(value)}% Fire Resistance`,
  freeHintPerRoom: (value) => value > 0 ? `First ${value === 1 ? "hint is" : `${value} hints are`} free each room` : "",
  goldFindPercent: (value) => `${plus(value)}% Gold Find`,
  healthRegen: (value) => `${plus(value)} Life Recovered per Room`,
  incomingDamagePercent: (value) => value > 0 ? `${plus(value)}% Damage Taken` : `${value}% Damage Taken`,
  increasedHealingReceivedPercent: (value) => `${plus(value)}% Healing Received`,
  increasedLootDropChancePercent: (value) => `${plus(value)}% Item Drop Chance`,
  increasedRareDropChancePercent: (value) => `${plus(value)}% Rare Drop Chance`,
  lifeOnKill: (value) => `${plus(value)} Life on Completion`,
  lifeStealPercent: (value) => `${plus(value)}% Life Steal`,
  lightningDamage: (value) => `${plus(value)} Lightning Damage`,
  lightningResistPercent: (value) => `${plus(value)}% Lightning Resistance`,
  magicFindPercent: (value) => `${plus(value)}% Magic Find`,
  maxLife: (value) => `${plus(value)} Maximum Life`,
  noRunDamagePercent: (value) => value > 0 ? `${plus(value)}% Submit Damage if Run was not used` : "",
  parryChancePercent: (value) => `${plus(value)}% Parry Chance`,
  physicalDamage: (value) => `${plus(value)} Physical Damage`,
  physicalResistPercent: (value) => `${plus(value)}% Physical Resistance`,
  poisonDamage: (value) => `${plus(value)} Poison Damage`,
  poisonResistPercent: (value) => `${plus(value)}% Poison Resistance`,
  reducedEnemyArmorPercent: (value) => `${lower(value)}% Enemy Armor`,
  reducedEnemyDamagePercent: (value) => `${lower(value)}% Enemy Damage`,
  relicChoiceBonus: (value) => value > 0 ? `${plus(value)} Relic Reward ${value === 1 ? "Choice" : "Choices"}` : "",
  relicRerollBonus: (value) => value > 0 ? `${plus(value)} Relic Reward ${value === 1 ? "Reroll" : "Rerolls"}` : "",
  revealTopicCount: (value) => value > 0 ? `Reveals ${value} extra question ${value === 1 ? "tag" : "tags"}` : "",
  revivePercent: (value) => value > 0 ? `Revives once per room at ${value}% life` : "",
  shopDiscountPercent: (value) => value > 0 ? `${plus(value)}% Shop Discount` : "",
  shopPriceIncreasePercent: (value) => value > 0 ? `${plus(value)}% Shop Prices` : "",
  shopRelicStock: (value) => value > 0 ? `${plus(value)} Shop Relic ${value === 1 ? "Listing" : "Listings"}` : "",
  skipRelicMetaBonus: (value) => value > 0 ? `${plus(value)} Insight when Skipping Relics` : "",
  submitFailDamageStackPercent: (value) => value > 0 ? `${plus(value)}% Submit Damage per Wrong Answer this room` : "",
  timerDamagePercent: (value) => value > 0 ? `${plus(value)}% Submit Damage from remaining time` : "",
  timerPenaltyPercent: (value) => value > 0 ? `${value}% Shorter Question Timer` : "",
  timerPauseSeconds: (value) => value > 0 ? `Timer starts with ${value}s grace` : "",
  resistancePenetrationPercent: (value) => `${plus(value)}% Resistance Penetration`
};

export function formatModifier(key: ItemModifierKey, value: number) {
  return MODIFIER_FORMATTERS[key]?.(value) || "";
}
