import type { ItemModifierKey } from "../types/study";

const plus = (value: number) => value > 0 ? `+${value}` : `${value}`;
const lower = (value: number) => value > 0 ? `-${value}` : `+${Math.abs(value)}`;

export const MODIFIER_FORMATTERS: Partial<Record<ItemModifierKey, (value: number) => string>> = {
  accuracyPercent: (value) => `${plus(value)}% Attack Rating`,
  armor: (value) => `${plus(value)} Armor`,
  armorPenetrationPercent: (value) => `${plus(value)}% Armor Penetration`,
  blockChancePercent: (value) => `${plus(value)}% Block Chance`,
  blockFirstHit: (value) => value > 0 ? "Blocks the first hit in each room" : "",
  bossRelicChoiceBonus: (value) => value > 0 ? `${plus(value)} Boss Relic Reward ${value === 1 ? "Choice" : "Choices"}` : "",
  bossShopRelicStock: (value) => value > 0 ? `${plus(value)} Boss Relic Shop Listing` : "",
  bonusDamageVsElitesPercent: (value) => `${plus(value)}% Damage to Elites`,
  bonusDamageWhileFullHealthPercent: (value) => `${plus(value)}% Damage at Full Life`,
  bonusDamageWhileLowHealthPercent: (value) => `${plus(value)}% Damage While Wounded`,
  bossEntryHeal: (value) => value > 0 ? `Heal ${value} when entering a boss room` : "",
  blockBreakDamagePercent: (value) => value > 0 ? `Breaking enemy Block deals ${value}% of it as bonus damage` : "",
  blockedEnemyDamagePercent: (value) => value > 0 ? `Deal ${value}% more damage while the enemy has Block` : "",
  bonusXpPercent: (value) => `${plus(value)}% Experience Gained`,
  coldDamage: (value) => `${plus(value)} Cold Damage`,
  coldResistPercent: (value) => `${plus(value)}% Cold Resistance`,
  combatClearMeta: (value) => value > 0 ? `Whenever you clear combat, gain ${value} Insight` : "",
  combatStartBlock: (value) => value > 0 ? `At the start of each combat, gain ${value} Block` : "",
  combatStartHeal: (value) => value > 0 ? `At the start of each combat, heal ${value} HP` : "",
  criticalChancePercent: (value) => `${plus(value)}% Critical Strike Chance`,
  criticalDamagePercent: (value) => `${plus(value)}% Critical Strike Damage`,
  damageReduction: (value) => `${lower(value)} Damage Taken`,
  damageVsArraysPercent: (value) => value > 0 ? `If the question has an Arrays tag, deal ${plus(value)}% damage` : "",
  damageVsBfsPercent: (value) => value > 0 ? `If the question has a BFS tag, deal ${plus(value)}% damage` : "",
  damageVsDfsPercent: (value) => value > 0 ? `If the question has a DFS tag, deal ${plus(value)}% damage` : "",
  damageVsDynamicProgrammingPercent: (value) => value > 0 ? `If the question has a Dynamic Programming tag, deal ${plus(value)}% damage` : "",
  damageVsGraphsPercent: (value) => value > 0 ? `If the question has a Graphs tag, deal ${plus(value)}% damage` : "",
  damageVsHashMapPercent: (value) => value > 0 ? `If the question has a Hash Map tag, deal ${plus(value)}% damage` : "",
  damageVsStringsPercent: (value) => value > 0 ? `If the question has a Strings tag, deal ${plus(value)}% damage` : "",
  damageVsTreesPercent: (value) => value > 0 ? `If the question has a Trees tag, deal ${plus(value)}% damage` : "",
  debuffResistPercent: (value) => value > 0 ? `${plus(value)}% chance to resist enemy debuffs` : "",
  dodgeChancePercent: (value) => `${plus(value)}% Dodge Chance`,
  eliteDropBonusPercent: (value) => value > 0 ? `${value}% chance Elite rewards show +1 choice` : "",
  eliteStartHealthReductionPercent: (value) => value > 0 ? `Elite enemies start combat with ${value}% less HP` : "",
  eliteRelicChoiceBonus: (value) => value > 0 ? `${plus(value)} Elite Relic Reward ${value === 1 ? "Choice" : "Choices"}` : "",
  enemyVulnerableSubmits: (value) => value > 0 ? `At combat start, apply ${value} Vulnerable to the enemy` : "",
  enemyWeakSubmits: (value) => value > 0 ? `At combat start, apply ${value} Weak to the enemy` : "",
  enhancedDamagePercent: (value) => `${plus(value)}% Enhanced Damage`,
  executeChancePercent: (value) => `${plus(value)}% Execute Chance`,
  extraAttackChancePercent: (value) => `${plus(value)}% Chance for an Extra Hit`,
  firstSubmitDamagePercent: (value) => value > 0 ? `First submit each room deals ${plus(value)}% damage` : "",
  fireDamage: (value) => `${plus(value)} Fire Damage`,
  fireResistPercent: (value) => `${plus(value)}% Fire Resistance`,
  freeHintPerRoom: (value) => value > 0 ? `First ${value === 1 ? "hint is" : `${value} hints are`} free each room` : `${Math.abs(value)} fewer free ${Math.abs(value) === 1 ? "hint" : "hints"} each room`,
  goldFindPercent: (value) => `${plus(value)}% Gold Find`,
  goldGainHeal: (value) => value > 0 ? `Whenever you gain Gold, heal ${value} HP` : "",
  healthRegen: (value) => value > 0 ? `${plus(value)} Life after each room` : `${value} Life after each room`,
  hexConfusedImmune: (value) => value > 0 ? "You cannot become Hexed or Confused" : "",
  incomingDamagePercent: (value) => value > 0 ? `${plus(value)}% Damage Taken` : `${value}% Damage Taken`,
  increasedHealingReceivedPercent: (value) => `${plus(value)}% Healing Received`,
  increasedLootDropChancePercent: (value) => `${plus(value)}% Reward Upgrade Chance`,
  increasedRareDropChancePercent: (value) => `${plus(value)}% Rare Drop Chance`,
  lowHealthClearHeal: (value) => value > 0 ? `After a clear below half Life, heal ${value}` : "",
  lifeOnKill: (value) => `${plus(value)} Life on Completion`,
  lifeStealPercent: (value) => `${plus(value)}% Life Steal`,
  lightningDamage: (value) => `${plus(value)} Lightning Damage`,
  lightningResistPercent: (value) => `${plus(value)}% Lightning Resistance`,
  magicFindPercent: (value) => `${plus(value)}% Magic Find`,
  maxLife: (value) => `${plus(value)} Maximum Life`,
  minimumSubmitDamage: (value) => value > 0 ? `Correct submits deal at least ${value} health damage after Block` : "",
  monsterDefeatHeal: (value) => value > 0 ? `Whenever a monster is defeated, heal ${value} HP` : "",
  noHintDamagePercent: (value) => value > 0 ? `${plus(value)}% Submit Damage before using hints` : "",
  noRunDamagePercent: (value) => value > 0 ? `${plus(value)}% Submit Damage if Run was not used` : "",
  parryChancePercent: (value) => `${plus(value)}% Parry Chance`,
  physicalDamage: (value) => `${plus(value)} Physical Damage`,
  physicalResistPercent: (value) => `${plus(value)}% Physical Resistance`,
  poisonDamage: (value) => `${plus(value)} Poison Damage`,
  poisonResistPercent: (value) => `${plus(value)}% Poison Resistance`,
  preventFirstHpLoss: (value) => value > 0 ? "Prevent the first time you would lose HP each combat" : "",
  potionDurationBonus: (value) => value > 0 ? `Potions last ${plus(value)} ${value === 1 ? "room" : "rooms"}` : "",
  reducedEnemyArmorPercent: (value) => `${lower(value)}% Enemy Armor`,
  reducedEnemyDamagePercent: (value) => `${lower(value)}% Enemy Damage`,
  relicChoiceBonus: (value) => value > 0 ? `${plus(value)} Relic Reward ${value === 1 ? "Choice" : "Choices"}` : `${value} Relic Reward ${Math.abs(value) === 1 ? "Choice" : "Choices"}`,
  relicRerollBonus: (value) => value > 0 ? `${plus(value)} Relic Reward ${value === 1 ? "Reroll" : "Rerolls"}` : `${value} Relic Reward ${Math.abs(value) === 1 ? "Reroll" : "Rerolls"}`,
  revealSubmitTestCount: (value) => value > 0 ? `Reveals ${value} failed submit ${value === 1 ? "test" : "tests"}` : "",
  revealTopicCount: (value) => value > 0 ? `Reveals ${value} extra question ${value === 1 ? "tag" : "tags"}` : "",
  revivePercent: (value) => value > 0 ? "1 Revive" : "",
  shopDiscountPercent: (value) => value > 0 ? `${plus(value)}% Shop Discount` : "",
  shopPriceIncreasePercent: (value) => value > 0 ? `${plus(value)}% Shop Prices` : "",
  shopRelicStock: (value) => value > 0 ? `${plus(value)} Shop Relic ${value === 1 ? "Listing" : "Listings"}` : "",
  smallHitToOneThreshold: (value) => value > 0 ? `Whenever you would lose ${value} or less HP, lose 1 HP instead` : "",
  skipRelicMaxLife: (value) => value > 0 ? `${plus(value)} Max Life when Skipping Relics` : "",
  skipRelicMetaBonus: (value) => value > 0 ? `${plus(value)} Insight when Skipping Relics` : "",
  submitFailDamageStackPercent: (value) => value > 0 ? `${plus(value)}% Submit Damage per Wrong Answer this room` : "",
  fifthSubmitDamagePercent: (value) => value > 0 ? `Every 5th submit deals ${plus(value)}% damage` : "",
  thornsDamage: (value) => value > 0 ? `When hit, deal ${value} damage back` : "",
  timerDamagePercent: (value) => value > 0 ? `${plus(value)}% Submit Damage from remaining time` : "",
  timerPenaltyPercent: (value) => value > 0 ? `${value}% Shorter Question Timer` : "",
  timerPauseSeconds: (value) => value > 0 ? `Timer starts with ${value}s grace` : "",
  treasureRelicChancePercent: (value) => value > 0 ? `${plus(value)}% Treasure Relic Chance` : "",
  vulnerableConstrictedImmune: (value) => value > 0 ? "You cannot become Vulnerable or Constricted" : "",
  resistancePenetrationPercent: (value) => `${plus(value)}% Guard Penetration`
};

export function formatModifier(key: ItemModifierKey, value: number) {
  return MODIFIER_FORMATTERS[key]?.(value) || "";
}
